spring.application.name=cine

spring.datasource.url=jdbc:postgresql://localhost:5432/cine_db
spring.datasource.username=postgres
spring.datasource.password=admin

#Compara entidades con la base de datos y actualiza
spring.jpa.hibernate.ddl-auto=update

#Muestra en la consola las consultas SQL que Hibernate ejecuta.
spring.jpa.show-sql=true

#Formatea consultas para que sean más legibles
spring.jpa.properties.hibernate.format_sql=true


